version: '3.7'
services:
  postgres:
    image: postgres:12.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asd
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
      